drop table if exists ty_mf_feature;
create table ty_mf_feature
(
mf_merchant_id string,
mf_which bigint,
mf_send_30 bigint,
mf_send_use_30 bigint,
mf_consumed_30 bigint,
mf_consume_user_30 bigint,
mf_rec_use_in_15_30 bigint,
mf_rate_use_in_15_rec_30 double,
mf_rate_use_in_15_use_30 double,
mf_use_day_avg_30 double,
mf_use_distance_avg_30 double,
mf_rate_use_send_30 double,
mf_rate_consume_user_consume_30 double,
mf_rate_send_use_consume_user_30 double,
mf_rate_send_use_user_30 double,
mf_send_60 bigint,
mf_send_use_60 bigint,
mf_consumed_60 bigint,
mf_consume_user_60 bigint,
mf_rec_use_in_15_60 bigint,
mf_rate_use_in_15_rec_60 double,
mf_rate_use_in_15_use_60 double,
mf_use_day_avg_60 double,
mf_use_distance_avg_60 double,
mf_rate_use_send_60 double,
mf_rate_consume_user_consume_60 double,
mf_rate_send_use_consume_user_60 double,
mf_rate_send_use_user_60 double,
mf_rec_future bigint,
mf_rec_cptype_future bigint,
mf_rec_utype_future bigint
);