drop table if exists ty_ucf_feature;
create table ty_ucf_feature
(
ucf_user_id string,
ucf_merchant_id string,
ucf_coupon_id string,
ucf_date_received string,
ucf_date_pay string,
ucf_which bigint,
ucf_rec_30 bigint,
ucf_rec_use_30 bigint,
ucf_rec_use_in_15_30 bigint,
ucf_rate_use_rec_30 double,
ucf_rate_use_in_15_rec_30 double,
ucf_rate_use_in_15_use_30 double,
ucf_use_day_avg_30 double,
ucf_rec_60 bigint,
ucf_rec_use_60 bigint,
ucf_rec_use_in_15_60 bigint,
ucf_rate_use_rec_60 double,
ucf_rate_use_in_15_rec_60 double,
ucf_rate_use_in_15_use_60 double,
ucf_use_day_avg_60 double,
ucf_week_0 bigint,
ucf_week_1 bigint,
ucf_week_2 bigint,
ucf_week_3 bigint,
ucf_week_4 bigint,
ucf_week_5 bigint,
ucf_week_6 bigint,
ucf_count_rec_bef bigint,
ucf_count_rec_after bigint,
ucf_days_rec_bef bigint,
ucf_days_rec_after bigint,
ucf_man double,
ucf_disc_rate double,
ucf_distance double,
ucf_rec_future bigint,
label_reg double,
label bigint
);