drop table if exists ty_uf_feature;
create table ty_uf_feature
(
uf_user_id string,
uf_which bigint,
uf_rec_30 bigint,
uf_rec_use_30 bigint,
uf_consume_30 bigint,
uf_consume_merchant_30 bigint,
uf_rec_use_in_15_30 bigint,
uf_rate_use_rec_30 double,
uf_rate_use_in_15_rec_30 double,
uf_rate_use_in_15_use_30 double,
uf_use_day_avg_30 double,
uf_use_distance_avg_30 double,
uf_rate_consume_merchant_consume_30 double,
uf_rate_rec_use_consume_merchant_30 double,
uf_rate_rec_use_merchant_30 double,
uf_rec_60 bigint,
uf_rec_use_60 bigint,
uf_consume_60 bigint,
uf_consume_merchant_60 bigint,
uf_rec_use_in_15_60 bigint,
uf_rate_use_rec_60 double,
uf_rate_use_in_15_rec_60 double,
uf_rate_use_in_15_use_60 double,
uf_use_day_avg_60 double,
uf_use_distance_avg_60 double,
uf_rate_consume_merchant_consume_60 double,
uf_rate_rec_use_consume_merchant_60 double,
uf_rate_rec_use_merchant_60 double,
uf_rec_future bigint,
uf_rec_cptype_future bigint,
uf_rec_mctype_future bigint
);