drop table if exists ty_umf_feature;
create table ty_umf_feature
(
umf_user_id string,
umf_merchant_id string,
umf_which bigint,
umf_rec_30 bigint,
umf_rec_use_30 bigint,
umf_consume_30 bigint,
umf_rec_use_type_30 bigint,
umf_rec_type_30 bigint,
umf_rec_use_in_15_30 bigint,
umf_rate_use_rec_30 double,
umf_rate_use_in_15_rec_30 double,
umf_rate_use_in_15_use_30 double,
umf_use_day_avg_30 double,
umf_rate_rec_consume_30 double,
umf_rate_rec_use_all_30 double,
umf_rate_rec_use_type_all_30 double,
umf_rec_60 bigint,
umf_rec_use_60 bigint,
umf_consume_60 bigint,
umf_rec_use_type_60 bigint,
umf_rec_type_60 bigint,
umf_rec_use_in_15_60 bigint,
umf_rate_use_rec_60 double,
umf_rate_use_in_15_rec_60 double,
umf_rate_use_in_15_use_60 double,
umf_use_day_avg_60 double,
umf_rate_rec_consume_60 double,
umf_rate_rec_use_all_60 double,
umf_rate_rec_use_type_all_60 double,
umf_rec_future bigint,
umf_rectype_future bigint
);